# Site settings
title: Android Kotlin Guides
email: your-email@domain.com
description: >
  Official guides for developing Kotlin on Android.
baseurl: "/kotlin-guides"
url: "https://android.github.io"

# Build settings
markdown: kramdown

collections:
  - changes

plugins:
  - octopress-autoprefixer
  - jekyll-redirect-from

exclude:
  - vendor
